kubectl create -f rabbitmq.yaml
kubectl create -f rabbitmqservice.yaml
kubectl create -f discover.yaml
kubectl create -f discoverservice.yaml
kubectl create -f edge.yaml
kubectl create -f turbine.yaml
kubectl create -f monitor.yaml
kubectl create -f orderline.yaml
kubectl create -f order.yaml
