apiVersion: v1
kind: ReplicationController
metadata:
  name: order
  labels:
    name: order
spec:
  replicas: 1
  selector:
    name: order
  template:
    metadata:
      labels:
        name: order
    spec:
      containers:
      - name: order
        image: "elipcero/orderservice"
        ports:
          - containerPort: 8080
